name: Debug Secrets

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets presence
        run: |
          if [ -z "${{ secrets.SERVER_IP }}" ]; then echo "SERVER_IP = EMPTY"; else echo "SERVER_IP = SET"; fi
          if [ -z "${{ secrets.SERVER_USER }}" ]; then echo "SERVER_USER = EMPTY"; else echo "SERVER_USER = SET"; fi
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then echo "SSH_PRIVATE_KEY = EMPTY"; else echo "SSH_PRIVATE_KEY = SET"; fi
