name: WordPress Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            echo "=== WordPress Deployment Started ==="
            
            # Create backup
            echo "Creating backup..."
            BACKUP_DIR="/home/$USER/backups"
            mkdir -p "$BACKUP_DIR"
            TIMESTAMP=$(date +'%Y%m%d_%H%M%S')
            sudo tar -czf "$BACKUP_DIR/wp_backup_$TIMESTAMP.tar.gz" -C /var/www html
            
            # Deploy files
            echo "Deploying files..."
            TEMP_DIR="/tmp/wp_deploy_$TIMESTAMP"
            mkdir -p "$TEMP_DIR"
            
            # Copy files from GitHub workspace
            cp -a /github/workspace/. "$TEMP_DIR/"
            
            # Sync to web directory (exclude sensitive files)
            sudo rsync -a --delete \
              --exclude ".git/" \
              --exclude ".github/" \
              --exclude "wp-config.php" \
              "$TEMP_DIR/" /var/www/html/
            
            # Set permissions
            echo "Setting permissions..."
            sudo chown -R www-data:www-data /var/www/html
            sudo find /var/www/html -type d -exec chmod 755 {} \;
            sudo find /var/www/html -type f -exec chmod 644 {} \;
            
            # Secure wp-config.php
            if [ -f "/var/www/html/wp-config.php" ]; then
              sudo chmod 600 /var/www/html/wp-config.php
            fi
            
            # Restart web server
            echo "Restarting web server..."
            sudo systemctl restart apache2 2>/dev/null || sudo systemctl restart nginx 2>/dev/null || echo "No web server to restart"
            
            # Cleanup
            sudo rm -rf "$TEMP_DIR"
            
            echo "=== Deployment Completed Successfully ==="
